services:
  # 1. Servicio de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: pemex_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-pemex_db}
      MYSQL_USER: ${DB_USER:-pemex_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pemex_password}
    ports:
      - "3307:3306" # Usamos el puerto 3307 para evitar conflictos con tu MySQL local
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Inyecta las tablas al iniciar

  # 2. Servicio del Backend (Python/Flask + LibreOffice)
  api:
    build: ./backend
    container_name: pemex_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=production
      - DB_HOST=db
      - DB_USER=${DB_USER:-pemex_user}
      - DB_PASSWORD=${DB_PASSWORD:-pemex_password}
      - DB_NAME=${DB_NAME:-pemex_db}
    depends_on:
      - db # Espera a que la base de datos arranque primero

  # 3. Servicio del Frontend (React + Nginx)
  interfaz:
    build: ./frontend
    container_name: pemex_frontend
    restart: always
    ports:
      - "3000:80" # Nginx corre en el puerto 80 dentro del contenedor
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api # Espera a que el backend esté listo

volumes:
  db_data:
